name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if Secrets are Accessible
        run: |
          if [[ -z "${{ secrets.DOCKERHUB_USERNAME }}" || -z "${{ secrets.DOCKERHUB_PASSWORD }}" ]]; then
            echo "One or both secrets are not set."
          else
            echo "Secrets are accessible."
          fi

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/testdeployment:latest .

      - name: List Docker images
        run: docker images

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/testdeployment:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into the server and deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/testdeployment:latest

            # Stop and remove any existing container
            docker stop test_container || true
            docker rm test_container || true

            # Run the new container
            docker run -d --name test_container ${{ secrets.DOCKERHUB_USERNAME }}/testdeployment:latest