name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "Username: ${{ secrets.DOCKER_USERNAME }}"
          echo "Password: ${{ secrets.DOCKER_PASSWORD }}"  # Be careful with this line

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/testdeployment:latest .

      - name: List Docker images
        run: docker images

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/testdeployment:latest
